/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class beer_cheese_jni_MyThread */

#ifndef _Included_beer_cheese_jni_MyThread
#define _Included_beer_cheese_jni_MyThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     beer_cheese_jni_MyThread
 * Method:    start0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_beer_cheese_jni_MyThread_start0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
