spring:
  jpa:
    database: h2
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: wuxc
    password: helloxc
    driver-class-name:
    url: jdbc:h2:~/test
