spring:
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: wuxc
    password: helloxc
    driver-class-name:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
