spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: root
    password: xc514xxx
    driver-class-name:
    url: jdbc:mysql://localhost:3306/code_demo?serverTimezone=Asia/Shanghai
